---
- name: Stop Wazuh
  community.docker.docker_compose_v2:
    project_src: "{{ wazuh_docker_dir }}"
    state: absent
  tags:
    - admin-password

- name: Generate Wazuh indexer password hash
  ansible.builtin.expect:
    command: >
      docker run --rm -ti wazuh/wazuh-indexer:4.14.5 bash
      /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
    responses:
      (?i)password: "{{ wazuh_admin_password }}"
  register: wazuh_hash_cmd
  tags:
    - admin-password

- name: Replace admin hash in internal_users.yml
  ansible.builtin.replace:
    path: "{{ wazuh_docker_dir }}/config/wazuh_indexer/internal_users.yml"
    regexp: '(^admin:\n\s+hash: ").*(")'
    replace: '\1{{ wazuh_hash_cmd.stdout_lines[1] }}\2'
  tags:
    - admin-password

- name: Start Wazuh
  community.docker.docker_compose_v2:
    project_src: "{{ wazuh_docker_dir }}"
    state: present
  tags:
    - admin-password

- name: Wait until OpenSearch is fully initialized inside container
  ansible.builtin.shell: |
    docker exec wazuh-wazuh.indexer-1 bash -c '
      curl -sk https://localhost:9200 >/dev/null
    '
  register: opensearch_ready
  retries: 60
  delay: 10
  until: opensearch_ready.rc == 0
  tags:
    - admin-password

- name: Apply Wazuh indexer admin password
  ansible.builtin.shell: |
    docker exec wazuh-wazuh.indexer-1 bash -c '
      export INSTALLATION_DIR=/usr/share/wazuh-indexer
      export CONFIG_DIR=$INSTALLATION_DIR/config

      export CACERT=$CONFIG_DIR/certs/root-ca.pem
      export KEY=$CONFIG_DIR/certs/admin-key.pem
      export CERT=$CONFIG_DIR/certs/admin.pem

      export JAVA_HOME=/usr/share/wazuh-indexer/jdk

      bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh \
        -cd $CONFIG_DIR/opensearch-security/ \
        -nhnv \
        -cacert $CACERT \
        -cert $CERT \
        -key $KEY \
        -p 9200 \
        -icl
    '
  register: securityadmin_result
  retries: 5
  delay: 15
  until: securityadmin_result.rc == 0
  tags:
    - admin-password
