---
- name: Deep merge ossec conf with defaults
  set_fact:
    wazuh_ossec_conf_merged: "{{ wazuh_ossec_conf_default | ansible.builtin.combine(wazuh_ossec_conf, list_merge='append', recursive=true) }}"

- name: Ensure ossec.conf file
  ansible.builtin.template:
    src: ossec.conf.j2
    dest: "{{ wazuh_docker_dir }}/config/wazuh_cluster/wazuh_manager.conf"
  notify:
    - Restart Wazuh | down
    - Restart Wazuh | up
    - Install python3-pip inside wazuh manager container
    - Install requests library inside wazuh manager container
  tags:
    - configuration

- name: Configure filebeat archive
  block:
  - name: Make filebeat.yml mutable 
    ansible.builtin.file:
      path: "{{ wazuh_docker_dir }}/manager/filebeat/filebeat.yml"
      attributes: -i

  - name: Toggle archives.enabled in filebeat.yml
    ansible.builtin.replace:
      path: "{{ wazuh_docker_dir }}/manager/filebeat/filebeat.yml"
      regexp: '(^\s+archives:\n\s+enabled:\s+)(true|false)'
      replace: '\1{{ "true" if wazuh_enable_archives else "false" }}'

  - name: Make filebeat.yml immutable 
    ansible.builtin.file:
      path: "{{ wazuh_docker_dir }}/manager/filebeat/filebeat.yml"
      attributes: +i

  when: wazuh_docker_bind_volumes_on_host
  notify:
    - Restart Wazuh | down
    - Restart Wazuh | up
    - Install python3-pip inside wazuh manager container
    - Install requests library inside wazuh manager container
  tags:
    - configuration

- name: Ensure custom-telegram integration file
  ansible.builtin.template:
    src: custom-telegram.j2
    dest: "{{ wazuh_docker_dir }}/manager/ossec/integrations/custom-telegram"
    owner: root
    group: 999
    mode: '0750'
  when: 
    - wazuh_docker_bind_volumes_on_host
    - wazuh_telegram_integration is defined
  notify:
    - Restart Wazuh | down
    - Restart Wazuh | up
    - Install python3-pip inside wazuh manager container
    - Install requests library inside wazuh manager container
  tags:
    - configuration
