---
- name: Ensure ossec.conf file
  ansible.builtin.template:
    src: ossec.conf.j2
    dest: "{{ wazuh_docker_dir }}/config/wazuh_cluster/wazuh_manager.conf"
  tags:
    - configuration

- name: Configure filebeat archive
  block:
  - name: Make filebeat.yml mutable 
    ansible.builtin.file:
      path: "{{ wazuh_docker_dir }}/manager/filebeat/filebeat.yml"
      attributes: -i

  - name: Toggle archives.enabled in filebeat.yml
    ansible.builtin.replace:
      path: "{{ wazuh_docker_dir }}/manager/filebeat/filebeat.yml"
      regexp: '(^\s+archives:\n\s+enabled:\s+)(true|false)'
      replace: '\1{{ "true" if wazuh_enable_archives else "false" }}'

  - name: Make filebeat.yml immutable 
    ansible.builtin.file:
      path: "{{ wazuh_docker_dir }}/manager/filebeat/filebeat.yml"
      attributes: +i

  when: wazuh_docker_bind_volumes_on_host
  tags:
    - configuration

- name: Restart Wazuh | down
  community.docker.docker_compose_v2:
    project_src: "{{ wazuh_docker_dir }}"
    state: absent
  tags:
    - configuration

- name: Restart Wazuh | up
  community.docker.docker_compose_v2:
    project_src: "{{ wazuh_docker_dir }}"
    state: present
  tags:
    - configuration
