---
- name: Install Wazuh
  ansible.builtin.include_tasks: "install.yml"

- name: Set admin password
  ansible.builtin.include_tasks: "admin-password.yml"

- name: Set ossec conf file
  ansible.builtin.include_tasks: "configuration.yml"
